const PAGE_ACCESS_TOKEN = process.env.PAGE_ACCESS_TOKEN;
const VERIFY_TOKEN = process.env.VERIFY_TOKEN;
const EVENT_TTL_MS = 10 * 60 * 1000;
const BATCH_TTL_MS = 15 * 60 * 1000;
const BATCH_DETAIL_PREVIEW_LIMIT = 7;
const BATCH_HISTORY_BUTTON_THRESHOLD = 8;
const MAX_MESSAGE_LENGTH = 600;
const GUEST_LOOKUP_TTL_MS = 5 * 60 * 1000;

module.exports = {
    PAGE_ACCESS_TOKEN,
    VERIFY_TOKEN,
    EVENT_TTL_MS,
    BATCH_TTL_MS,
    BATCH_DETAIL_PREVIEW_LIMIT,
    BATCH_HISTORY_BUTTON_THRESHOLD,
    MAX_MESSAGE_LENGTH,
    GUEST_LOOKUP_TTL_MS,
};
